stages:
  data_ingestion:
    cmd: PYTHONPATH=. python src/CNN/pipeline/stage_01_data_ingestion.py
    deps:
      - src/CNN/pipeline/stage_01_data_ingestion.py
      - config/config.yml
    outs:
      - artifacts/data_ingestion/Chest-CT-Scan-data


  prepare_base_model:
    cmd: python src/CNN/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/CNN/pipeline/stage_02_prepare_base_model.py
      - config/config.yml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model

  training:
    cmd: python src/CNN/pipeline/stage_03_model_trainer.py
    deps:
      - src/CNN/pipeline/stage_03_model_trainer.py
      - config/config.yml
      - artifacts/data_ingestion/Chest-CT-Scan-data
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.hs

  evaluation:
    cmd: python src/CNN/pipeline/stage_04_evaluation.py
    deps:
      - src/CNN/pipeline/stage_04_evaluation.py
      - config/config.yml
      - artifacts/data_ingestion/Chest-CT-Scan-data
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    
    metrics:
      - scores.json
          cache:false